REM Remove unnecessary files generated by compiler in both the 
REM MPLAB 8 and MPLAB X project directories.

echo Removing *.$$$ files...
del MPLAB.8\*.$$$ /f /q /s
echo.

echo Removing *.as files...
del MPLAB.8\*.as /f /q /s
echo.

echo Removing *.bkx files...
del MPLAB.8\*.bkx /f /q /s
echo.

echo Removing *.cce files...
del MPLAB.8\*.cce /f /q /s
echo.

echo Removing *.cod files...
del MPLAB.8\*.cod /f /q /s
echo.

echo Removing *.cof files...
del MPLAB.8\*.cof /f /q /s
echo.

echo Removing *.err files...
del MPLAB.8\*.err /f /q /s
echo.

echo Removing *.hex files...
del MPLAB.8\*.hex /f /q 
echo.

echo Removing *.i files...
del MPLAB.8\*.i /f /q /s
echo.

echo Removing *.lde files...
del MPLAB.8\*.lde /f /q /s
echo.

echo Removing *.lst files...
del MPLAB.8\*.lst /f /q /s
echo.

echo Removing *.obj files...
del MPLAB.8\*.obj /f /q /s
echo.

echo Removing *.o files...
del MPLAB.8\*.o /f /q /s
echo.

echo Removing *.rlf files...
del MPLAB.8\*.rlf /f /q /s
echo.

echo Removing *.sym files...
del MPLAB.8\*.sym /f /q /s
echo.

echo Removing *.sdb files...
del MPLAB.8\*.sdb /f /q /s
echo.

echo Removing *.wat files...
del MPLAB.8\*.wat /f /q /s
echo.

echo Removing *.mcs files...
del MPLAB.8\*.mcs /f /q /s
echo.

echo Removing *.mptags files...
del MPLAB.8\*.mptags /f /q /s
echo.

echo Removing *.tagsrc files...
del MPLAB.8\*.tagsrc /f /q /s
echo.

echo Removing *.map files...
del MPLAB.8\*.map /f /q /s
echo.

echo Removing *.elf files...
del MPLAB.8\*.elf /f /q /s
echo.

echo Removing *.dep files...
del MPLAB.8\*.dep /f /q /s
echo.

echo Removing *.hxl files...
del MPLAB.8\*.hxl /f /q /s
echo.

echo Removing *.p1 files...
del MPLAB.8\*.p1 /f /q /s
echo.

echo Removing *.pre files...
del MPLAB.8\*.pre /f /q /s
echo.

echo Removing funclist file...
del MPLAB.8\funclist /f /q /s
echo.

echo Removing funclist file...
del MPLAB.X\funclist /f /q /s
echo.

rd MPLAB.X\build /S /Q
rd MPLAB.X\dist  /S /Q

echo Done.