@echo off
REM Remove files generated by compiler in this directory
REM and all subdirectories.

del *.$$$ /f /q /s
del *.bkx /f /q /s
del *.cce /f /q /s
del *.cod /f /q /s
del *.cof /f /q /s
del *.err /f /q /s
del *.hex /f /q /s
del *.i /f /q /s
del *.lde /f /q /s
del *.lst /f /q /s
del *.obj /f /q /s
del *.o /f /q /s
del *.rlf /f /q /s
del *.sym /f /q /s
del *.sdb /f /q /s
del *.wat /f /q /s
del *.mcs /f /q /s
del *.mptags /f /q /s
del *.tagsrc /f /q /s
del *.map /f /q /s
del *.elf /f /q /s

rd Objects /S /Q