/******************************************************************************
*
* This demo shows how to display JPEG files from internal and external memories.
*
******************************************************************************
* The "Font and Bitmap Converter" should be used to add JPEG files as C arrays
* for the internal flash and as Intel HEX file for the external memory. All C files
* generated by this utility must be added in your project. Intel HEX file must be
* programmed into the external memory. For Graphics PICtail 2 and Graphics PICtail 3
* "Graphics PICtail Board Memory Programmer" project can be used to program the HEX file
* into flash memory on these PICtails.
*
* The header file for the external memory access driver must be added into JPEGImage.h.
* In the external memory access driver the data array reading function must be implemented.
* The function must be specified in JPEGImage.h file (see the header file for details).
*
* JPEG displaying example:
*
* extern BITMAP_FLASH     jpegFileInInternalFlash;
* extern BITMAP_EXTERNAL  jpegFileInExternalFlash;

* int main(){
*   ExternalMemoryDriverInit(); // initialize driver for external memory used to store JPEG files
*   GraphInit();                // initialize graphics library. GOLInit() can be used instead
*   JPEGInit();                 // initialize JPEG decoder
*   JPEGPutImage(10,10,&jpegFileInInternalFlash); // display picture from internal memory
*   JPEGPutImage(20,13,&jpegFileInExternalFlash); // display picture from external memory
* }
*
* JPEGImage.h/JPEGImage.c module depends on files from the Graphics Library.
*
* To add the JPEGImage.h/JPEGImage.c module to the Graphics Library project the following
* files should be included:
*   > ImageDecoder.c - Image Decoders library file
*   > JpegDecoder.c - Image Decoders library file
*   > jidctint.c - Image Decoders library file
*   > JPEGImage.c - contains JPEGInit() and JPEGPutImage(...) implementations
*   > ImageDecoderConfig.h - must be in the project folder
*   > JPEGImage.h - must be in the project folder
*   > C files generated by the utility with JPEG images located in internal memory
*   > C reference files generated by the utility with references to JPEG images located
*     in external memory (these files are created for each HEX file)
*
*******************************************************************************
* FileName:        MainDemo.c
* Dependencies:    Image decoding library, Graphics Library, SST25 and SST39 flash drivers
* Processor:       PIC24F, PIC24H, dsPIC, PIC32
* Compiler:        C30 v2.01/C32 v0.00.18
* Company:         Microchip Technology, Inc.

 * Software License Agreement
 *
 * Copyright © 2009 Microchip Technology Inc.  All rights reserved.
 * Microchip licenses to you the right to use, modify, copy and distribute
 * Software only when embedded on a Microchip microcontroller or digital
 * signal controller, which is integrated into your product or third party
 * product (pursuant to the sublicense terms in the accompanying license
 * agreement).  
 *
 * You should refer to the license agreement accompanying this Software
 * for additional information regarding your rights and obligations.
 *
 * SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
 * OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
 * PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
 * OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
 * BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
 * DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
 * INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
 * COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
 * CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
 * OR OTHER SIMILAR COSTS.

Author                 Date           Comments
--------------------------------------------------------------------------------
Anton Alkhimenok       05-May-2009
*******************************************************************************/
#include "MainDemo.h"

// Configuration bits
#if defined(__dsPIC33F__) || defined(__PIC24H__)
_FOSCSEL(FNOSC_PRI);
_FOSC(FCKSM_CSECMD &OSCIOFNC_OFF &POSCMD_XT);
_FWDT(FWDTEN_OFF);
#elif defined(__PIC32MX__)
    #pragma config FPLLODIV = DIV_1, FPLLMUL = MUL_20, FPLLIDIV = DIV_2, FWDTEN = OFF, FCKSM = CSECME, FPBDIV = DIV_1
    #pragma config OSCIOFNC = ON, POSCMOD = XT, FSOSCEN = ON, FNOSC = PRIPLL
    #pragma config CP = OFF, BWP = OFF, PWP = OFF
#else
    #if defined(__PIC24FJ256GB110__)
_CONFIG1(JTAGEN_OFF & GCP_OFF & GWRP_OFF & COE_OFF & FWDTEN_OFF & ICS_PGx2)
_CONFIG2(0xF7FF & IESO_OFF & FCKSM_CSDCMD & OSCIOFNC_OFF & POSCMOD_HS & FNOSC_PRIPLL & PLLDIV_DIV2 & IOL1WAY_OFF)
    #endif
    #if defined(__PIC24FJ256GA110__)
_CONFIG1(JTAGEN_OFF & GCP_OFF & GWRP_OFF & COE_OFF & FWDTEN_OFF & ICS_PGx2)
_CONFIG2(IESO_OFF & FCKSM_CSDCMD & OSCIOFNC_OFF & POSCMOD_HS & FNOSC_PRIPLL & IOL1WAY_OFF)
    #endif
    #if defined(__PIC24FJ128GA010__)
_CONFIG2(FNOSC_PRIPLL & POSCMOD_XT) // Primary XT OSC with PLL
_CONFIG1(JTAGEN_OFF & FWDTEN_OFF)   // JTAG off, watchdog timer off
    #endif
	#if defined (__PIC24FJ256GB210__)
_CONFIG1( WDTPS_PS32768 & FWPSA_PR128 & ALTVREF_ALTVREDIS & WINDIS_OFF & FWDTEN_OFF & ICS_PGx2 & GWRP_OFF & GCP_OFF & JTAGEN_OFF) 
_CONFIG2( POSCMOD_HS & IOL1WAY_OFF & OSCIOFNC_OFF & OSCIOFNC_OFF & FCKSM_CSDCMD & FNOSC_PRIPLL & PLL96MHZ_ON & PLLDIV_DIV2 & IESO_OFF)
_CONFIG3( WPFP_WPFP255 & SOSCSEL_SOSC & WUTSEL_LEG & WPDIS_WPDIS & WPCFG_WPCFGDIS & WPEND_WPENDMEM) 
	#endif
	#if defined (__PIC24FJ256DA210__)
_CONFIG1( WDTPS_PS32768 & FWPSA_PR128 & ALTVREF_ALTVREDIS & WINDIS_OFF & FWDTEN_OFF & ICS_PGx2 & GWRP_OFF & GCP_OFF & JTAGEN_OFF) 
_CONFIG2( POSCMOD_HS & IOL1WAY_OFF & OSCIOFNC_OFF & OSCIOFNC_OFF & FCKSM_CSDCMD & FNOSC_PRIPLL & PLL96MHZ_ON & PLLDIV_DIV2 & IESO_OFF)
_CONFIG3( WPFP_WPFP255 & SOSCSEL_SOSC & WUTSEL_LEG & ALTPMP_ALTPMPEN & WPDIS_WPDIS & WPCFG_WPCFGDIS & WPEND_WPENDMEM) 
	#endif	
#endif


/////////////////////////////////////////////////////////////////////////////
// JPEG Files
/////////////////////////////////////////////////////////////////////////////
extern IMAGE_FLASH Logo;
extern IMAGE_EXTERNAL  Scene02;
extern IMAGE_EXTERNAL  Scene01;

#define DELAY_MS    1500

/* */

int main(void)
{

    #if defined(PIC24FJ256DA210_DEV_BOARD)
    
    _ANSG8 = 0; /* S1 */
    _ANSE9 = 0; /* S2 */
    _ANSB5 = 0; /* S3 */
        
    #else

    /////////////////////////////////////////////////////////////////////////////
    // ADC Explorer 16 Development Board Errata (work around 2)
    // RB15 should be output
    /////////////////////////////////////////////////////////////////////////////
    #ifndef MULTI_MEDIA_BOARD_DM00123
    LATBbits.LATB15 = 0;
    TRISBbits.TRISB15 = 0;
    #endif

    #endif

    /////////////////////////////////////////////////////////////////////////////
    #if defined(__dsPIC33F__) || defined(__PIC24H__)

    // Configure Oscillator to operate the device at 40Mhz
    // Fosc= Fin*M/(N1*N2), Fcy=Fosc/2
    // Fosc= 8M*40(2*2)=80Mhz for 8M input clock
    PLLFBD = 38;                    // M=40
    CLKDIVbits.PLLPOST = 0;         // N1=2
    CLKDIVbits.PLLPRE = 0;          // N2=2
    OSCTUN = 0;                     // Tune FRC oscillator, if FRC is used

    // Disable Watch Dog Timer
    RCONbits.SWDTEN = 0;

    // Clock switching to incorporate PLL
    __builtin_write_OSCCONH(0x03);  // Initiate Clock Switch to Primary

    // Oscillator with PLL (NOSC=0b011)
    __builtin_write_OSCCONL(0x01);  // Start clock switching
    while(OSCCONbits.COSC != 0b011);

    // Wait for Clock switch to occur	
    // Wait for PLL to lock
    while(OSCCONbits.LOCK != 1)
    { };     
    
    // Set PMD0 pin functionality to digital
    AD1PCFGL = AD1PCFGL | 0x1000;
       
    #elif defined(__PIC32MX__)
    INTEnableSystemMultiVectoredInt();
    SYSTEMConfigPerformance(GetSystemClock());
    #ifdef MULTI_MEDIA_BOARD_DM00123
        CPLDInitialize();
        CPLDSetGraphicsConfiguration(GRAPHICS_HW_CONFIG);
        CPLDSetSPIFlashConfiguration(SPI_FLASH_CHANNEL);
    #endif
    #endif

    // Initialize external memory
    #if defined (GFX_PICTAIL_V2) 
    SST39Init();
	InitGraph();                    // Initialize graphics
    #else 
	InitGraph();                    // Initialize graphics
    SST25Init();
    #endif

    #if defined(__dsPIC33FJ128GP804__) || defined(__PIC24HJ128GP504__)
    AD1PCFGL = 0xffff;
    #endif

    
	JPEGInit();                     // Initialize JPEG
    SetFont((void *) &GOLFontDefault);

    while(1)
    {
        #ifdef USE_JPEG_EXTERNAL
        // FROM EXTERNAL MEMORY
        JPEGPutImage(0, 0, &Scene01);
        SetColor(WHITE);
        OutTextXY(0, 0, "EXTERNAL MEMORY");
        DelayMs(DELAY_MS);
        JPEGPutImage(0, 0, &Scene02);
        SetColor(WHITE);
        OutTextXY(0, 0, "EXTERNAL MEMORY");
        DelayMs(DELAY_MS);
        #endif

        #ifdef USE_JPEG_FLASH
        // FROM INTERNAL FLASH
        JPEGPutImage(0, 0, &Logo);
        SetColor(WHITE);
        OutTextXY(0, 0, "INTERNAL FLASH");
        DelayMs(DELAY_MS);
        #endif
    }

    return (0);
}
