@echo off
REM Remove files generated by compiler in this directory
REM and all subdirectories.

:start
ECHO Erase all temp data? y or n?
:loop
set /p choice=
if not '%choice%'=='' set choice=%choice:~0,1%
if '%choice%'=='y' goto yes
if '%choice%'=='n' goto no
ECHO "%choice%" is not valid please try again
goto loop

:yes
cd ".."

ECHO *****************************************************************************
ECHO Removing USB Device - CDC - Basic Demo information
ECHO *****************************************************************************
cd "USB Device - CDC - Basic Demo\CDC - Basic Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO *****************************************************************************
ECHO Removing USB Device - CDC - Serial Emulator
ECHO *****************************************************************************
cd "USB Device - CDC - Serial Emulator\CDC - Serial Emulator"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Composite - HID + MSD
ECHO *****************************************************************************
cd "USB Device - Composite - HID + MSD\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Keyboard
ECHO *****************************************************************************
cd "USB Device - HID - Keyboard\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Mouse
ECHO *****************************************************************************
cd "USB Device - HID - Mouse\HID - Mouse - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Simple Custom Demo
ECHO *****************************************************************************
cd "USB Device - HID - Custom Demos\Generic HID - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - SD Card data logger
ECHO *****************************************************************************
cd "USB Device - Mass Storage - SD Card data logger\Mass Storage - Data Logger - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - Internal Flash
ECHO *****************************************************************************
cd "USB Device - Mass Storage - Internal Flash\Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - SD Card reader
ECHO *****************************************************************************
cd "USB Device - Mass Storage - SD Card reader\Mass Storage - SD Card Reader - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - MCHPUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB Device - MCHPUSB - Generic Driver Demo\Generic Driver Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - WinUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - HID - Keyboard
ECHO *****************************************************************************
cd "USB Host - HID - Keyboard\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Mass Storage - Thumb Drive Data Logger
ECHO *****************************************************************************
cd "USB Host - Mass Storage - Thumb Drive Data Logger\Mass Storage - Thumb Drive Data Logger"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - MCHPUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB Host - MCHPUSB - Generic Driver Demo\firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - CDC - Serial Demo
ECHO *****************************************************************************
cd "USB Host - CDC - Serial Demo\ACM - Serial RS232 Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer - Print Screen Demo
ECHO *****************************************************************************
cd "USB Host - Printer - Print Screen Demo\Print Screen Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer - Simple Full Sheet Demo
ECHO *****************************************************************************
cd "USB Host - Printer - Simple Full Sheet Demo\Simple Full Sheet Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer - Simple POS Demo
ECHO *****************************************************************************
cd "USB Host - Printer - Simple POS Demo\Simple POS Demo"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - MCHPUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB OTG - MCHPUSB - Generic Driver Demo\firmware"
call "CleanUp.bat"
cd "..\.."

:no
echo Done.